package View;

import Controller.Authorization;
import static com.sun.org.apache.xerces.internal.util.FeatureState.is;
import static com.sun.org.apache.xerces.internal.util.PropertyState.is;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import static java.awt.image.ImageObserver.HEIGHT;

import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.animation.FadeTransition;
import javafx.scene.layout.StackPane;
import javafx.util.Duration;
import javax.swing.JPanel;
import javax.swing.Timer;
import static sun.nio.cs.Surrogate.is;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AlexKarlov
 */
public class AuthFrame extends javax.swing.JFrame {
public int x;
int xx;
int yy;
    /**
     * Creates new form AuthFrame
     */
    public AuthFrame() {
        initComponents();
        pnl_overlay.setBackground(new Color(0,0,0,180));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        pnl_overlay = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_login = new javax.swing.JTextField();
        login_separator = new javax.swing.JSeparator();
        password_separator = new javax.swing.JSeparator();
        txt_pass = new javax.swing.JPasswordField();
        btnSignIn = new java.awt.Button();
        password_label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        login_label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("Authorization"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 113, 177));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Resources/1495891582_Gnome-Window-Close-48.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 50, 50));

        pnl_overlay.setBackground(new java.awt.Color(0, 109, 19));
        pnl_overlay.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_overlayMouseDragged(evt);
            }
        });
        pnl_overlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_overlayMousePressed(evt);
            }
        });
        pnl_overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(57, 52, 54));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Resources/1494814431_10.png"))); // NOI18N
        pnl_overlay.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Design, Create Awesome Swing UI");
        pnl_overlay.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        getContentPane().add(pnl_overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 500));

        jPanel2.setBackground(new java.awt.Color(0, 157, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(57, 52, 54));
        jLabel1.setText("Odessa, Copyright © 2017 Karlov.");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        txt_login.setBackground(new java.awt.Color(0, 157, 65));
        txt_login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_login.setForeground(new java.awt.Color(57, 113, 177));
        txt_login.setBorder(null);
        txt_login.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_loginFocusGained(evt);
            }
        });
        txt_login.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txt_loginCaretPositionChanged(evt);
            }
        });
        txt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_loginActionPerformed(evt);
            }
        });
        jPanel2.add(txt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 270, 30));

        login_separator.setBackground(new java.awt.Color(32, 34, 255));
        jPanel2.add(login_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 270, -1));

        password_separator.setBackground(new java.awt.Color(32, 34, 255));
        jPanel2.add(password_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 270, -1));

        txt_pass.setBackground(new java.awt.Color(0, 157, 65));
        txt_pass.setForeground(new java.awt.Color(255, 255, 255));
        txt_pass.setText("jPasswordField1");
        txt_pass.setBorder(null);
        txt_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passFocusGained(evt);
            }
        });
        jPanel2.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 270, 30));

        btnSignIn.setActionCommand("Войти");
        btnSignIn.setBackground(new java.awt.Color(255, 255, 255));
        btnSignIn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnSignIn.setForeground(new java.awt.Color(0, 157, 65));
        btnSignIn.setLabel("Sign in");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        jPanel2.add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 270, 40));

        password_label.setForeground(new java.awt.Color(57, 52, 54));
        password_label.setText("Password");
        jPanel2.add(password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, 20));

        jLabel5.setForeground(new java.awt.Color(57, 52, 54));
        jLabel5.setText("Please fill in all fields");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jLabel7.setForeground(new java.awt.Color(57, 52, 54));
        jLabel7.setText(" Designed by KarlovAS  ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, -1, -1));

        login_label.setForeground(new java.awt.Color(57, 113, 177));
        login_label.setText("Name");
        jPanel2.add(login_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 0, 490, 500));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Resources/Image-9677106-151861681-2-WebSmall_0_f862387a683cf6c32830ece6905283d7_1.jpg"))); // NOI18N
        jLabel6.setAlignmentY(0.0F);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_loginActionPerformed

    private void txt_loginCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_loginCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_loginCaretPositionChanged

    private void txt_loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_loginFocusGained
        // TODO add your handling code here:
        login_separator.setBackground(new Color(255, 255, 255));
        login_label.setForeground(new Color(255, 255, 255));
        password_label.setForeground(new Color(51, 52, 54));
        txt_login.setForeground(new Color(255, 255, 255));
        
    }//GEN-LAST:event_txt_loginFocusGained

    private void pnl_overlayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_overlayMousePressed
     // TODO add your handling code here:
     xx = evt.getX();
     yy = evt.getY();
    }//GEN-LAST:event_pnl_overlayMousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void pnl_overlayMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_overlayMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_pnl_overlayMouseDragged

    private void txt_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passFocusGained
        // TODO add your handling code here:
        password_separator.setBackground(new Color(255, 255, 255));
        password_label.setForeground(new Color(255, 255, 255));
       login_label.setForeground(new Color(51, 52, 54));
       txt_pass.setForeground(new Color(255, 255, 255));
       txt_pass.setText(null);
    }//GEN-LAST:event_txt_passFocusGained

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
       Authorization auth = new Authorization();
       auth.auth(txt_login.getText(), txt_pass.getText());
    }//GEN-LAST:event_btnSignInActionPerformed

    
 /*   void TimerAnimation(){
    
      javax.swing.Timer timer = new Timer(1, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
           nextStep();
        }
    } );
    timer.start();
    }
    
    void nextStep(){
       if(pnl_overlay.getWidth() >40){
       pnl_overlay.setSize(pnl_overlay.getWidth() -1, pnl_overlay.getHeight());
        jPanel2.setSize(jPanel2.getWidth() +1, jPanel2.getHeight());
       jPanel2.setLocation(jPanel2.getLocation().x-1, jPanel2.getLocation().y);
         repaint();
       }
      
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnSignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel login_label;
    private javax.swing.JSeparator login_separator;
    private javax.swing.JLabel password_label;
    private javax.swing.JSeparator password_separator;
    private javax.swing.JPanel pnl_overlay;
    private javax.swing.JTextField txt_login;
    private javax.swing.JPasswordField txt_pass;
    // End of variables declaration//GEN-END:variables
}
