/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DBControllerGroup;
import Controller.DBControllerStudent;
import Model.Tags;
import java.awt.Color;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Toolkit;
import java.util.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author AlexKarlov
 */
public class ManagerTools extends javax.swing.JFrame {
int xx;
int yy;
DBControllerStudent db;
DBControllerGroup dbg;
Tags tag;
protected  int studentId = 0;
 ArrayList<String> s = new ArrayList<String>();
    /**
     * Creates new form ManagerTools
     */
    public ManagerTools() {
        initComponents();
               pnl_new_group_1.setVisible(false);
               pnl_new_group_2.setVisible(false);
               db = new DBControllerStudent();
               dbg = new DBControllerGroup();
               tag = new Tags();
               setValueToTableStudent();
    }
private void setValueToTableStudent(){
     table_student.setModel(DbUtils.resultSetToTableModel(db.loadTable(tag.DB_NAME+"."+tag.STUDENT_TABLE, null)));
}
private void setValueToTableGroupStudent(){
               table_group.setModel(DbUtils.resultSetToTableModel(dbg.loadStudentGroupClear(null)));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        pnl_sidebar = new javax.swing.JPanel();
        menu_item_1 = new javax.swing.JLabel();
        menu_item_2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        pnl_menu = new javax.swing.JLayeredPane();
        pnl_student = new javax.swing.JPanel();
        pnl_header4 = new javax.swing.JPanel();
        lbl_exit_5 = new javax.swing.JLabel();
        lbl_logo4 = new javax.swing.JLabel();
        lbl_logoName4 = new javax.swing.JLabel();
        jgroup1 = new javax.swing.JLayeredPane();
        pnl_new_student = new javax.swing.JPanel();
        txt_header32 = new javax.swing.JLabel();
        txt_desc27 = new javax.swing.JLabel();
        jSeparator123 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        pnl_cmd_clear29 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        pnl_cmd_add29 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        txt_student_last_name = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        txt_student_name = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane29 = new javax.swing.JScrollPane();
        table_student = new javax.swing.JTable();
        txt_header30 = new javax.swing.JLabel();
        jSeparator119 = new javax.swing.JSeparator();
        txt_search_student = new javax.swing.JTextField();
        lbl_cmd_search_gorup1 = new javax.swing.JLabel();
        pnl_group = new javax.swing.JPanel();
        pnl_header = new javax.swing.JPanel();
        lbl_exit_1 = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        lbl_logoName = new javax.swing.JLabel();
        lbl_cmd_header_button_create = new javax.swing.JLabel();
        lbl_cmd_header_buttonNew = new javax.swing.JLabel();
        jgroup = new javax.swing.JLayeredPane();
        pnl_new_group_2 = new javax.swing.JPanel();
        txt_header27 = new javax.swing.JLabel();
        jSeparator115 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane28 = new javax.swing.JScrollPane();
        table_group = new javax.swing.JTable();
        txt_header29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_student_forGroup = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        pnl_cmd_clear28 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        pnl_cmd_add28 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        choice_group = new java.awt.Choice();
        txt_header31 = new javax.swing.JLabel();
        pnl_new_group_1 = new javax.swing.JPanel();
        txt_header26 = new javax.swing.JLabel();
        txt_desc26 = new javax.swing.JLabel();
        jSeparator111 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        pnl_cmd_clear26 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        pnl_cmd_add26 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane27 = new javax.swing.JScrollPane();
        jTable27 = new javax.swing.JTable();
        txt_header28 = new javax.swing.JLabel();
        jSeparator114 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        start_finish_date = new datechooser.beans.DateChooserCombo();
        choiceTeacher = new java.awt.Choice();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        choiceDescipline = new java.awt.Choice();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(54, 63, 73));
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pnl_sidebar.setBackground(new java.awt.Color(0, 157, 65));
        pnl_sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_sidebarMouseDragged(evt);
            }
        });
        pnl_sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_sidebarMousePressed(evt);
            }
        });

        menu_item_1.setBackground(new java.awt.Color(255, 255, 255));
        menu_item_1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_1.setForeground(new java.awt.Color(255, 255, 255));
        menu_item_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Resources/1495903055_user_male3.png"))); // NOI18N
        menu_item_1.setText("Студенты");
        menu_item_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_item_1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_item_1MousePressed(evt);
            }
        });

        menu_item_2.setBackground(new java.awt.Color(255, 255, 255));
        menu_item_2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu_item_2.setForeground(new java.awt.Color(255, 255, 255));
        menu_item_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Resources/1495903068_group.png"))); // NOI18N
        menu_item_2.setText("Группы");
        menu_item_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_item_2MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu_item_2MouseReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 83, 34));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Design, Create Awesome Swing UI");

        jLabel9.setForeground(new java.awt.Color(57, 52, 54));
        jLabel9.setText("Odessa, Copyright © 2017 Karlov.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Resources/User-50.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Виктория");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Менеджер");

        jPanel2.setBackground(new java.awt.Color(2, 181, 76));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Resources/1495901336_list.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator6)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(94, 94, 94))
            .addComponent(jSeparator7)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(17, 17, 17)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout pnl_sidebarLayout = new javax.swing.GroupLayout(pnl_sidebar);
        pnl_sidebar.setLayout(pnl_sidebarLayout);
        pnl_sidebarLayout.setHorizontalGroup(
            pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sidebarLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_sidebarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(menu_item_1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnl_sidebarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(menu_item_2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_sidebarLayout.setVerticalGroup(
            pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sidebarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(pnl_sidebarLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(menu_item_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(menu_item_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_menu.setLayout(new javax.swing.OverlayLayout(pnl_menu));

        pnl_student.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_studentMouseDragged(evt);
            }
        });
        pnl_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_studentMousePressed(evt);
            }
        });

        pnl_header4.setBackground(new java.awt.Color(0, 157, 65));
        pnl_header4.setPreferredSize(new java.awt.Dimension(453, 206));

        lbl_exit_5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_exit_5.setForeground(new java.awt.Color(57, 113, 177));
        lbl_exit_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Resources/1495903985_Gnome-Window-Close-32.png"))); // NOI18N
        lbl_exit_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit_5MouseClicked(evt);
            }
        });

        lbl_logo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Resources/1495925307_SEO_WEB_analytics.png"))); // NOI18N

        lbl_logoName4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbl_logoName4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logoName4.setText("AnalyticToo");

        javax.swing.GroupLayout pnl_header4Layout = new javax.swing.GroupLayout(pnl_header4);
        pnl_header4.setLayout(pnl_header4Layout);
        pnl_header4Layout.setHorizontalGroup(
            pnl_header4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_header4Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(lbl_logo4)
                .addGap(18, 18, 18)
                .addComponent(lbl_logoName4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_exit_5)
                .addGap(21, 21, 21))
        );
        pnl_header4Layout.setVerticalGroup(
            pnl_header4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_header4Layout.createSequentialGroup()
                .addGroup(pnl_header4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_header4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_exit_5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_header4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pnl_header4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_header4Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lbl_logoName4))
                            .addComponent(lbl_logo4, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jgroup1.setLayout(new javax.swing.OverlayLayout(jgroup1));

        pnl_new_student.setBackground(new java.awt.Color(255, 255, 255));
        pnl_new_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_new_studentMouseClicked(evt);
            }
        });

        txt_header32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_header32.setForeground(new java.awt.Color(34, 41, 50));
        txt_header32.setText("Студент");

        txt_desc27.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_desc27.setForeground(new java.awt.Color(34, 41, 50));
        txt_desc27.setText("Пожалуйста, заполните все поля");

        jSeparator123.setBackground(new java.awt.Color(1, 198, 83));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        pnl_cmd_clear29.setBackground(new java.awt.Color(255, 255, 255));
        pnl_cmd_clear29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 157, 65), 1, true));
        pnl_cmd_clear29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_cmd_clear29MouseClicked(evt);
            }
        });

        jLabel68.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(0, 157, 65));
        jLabel68.setText("Отмена");
        pnl_cmd_clear29.add(jLabel68);

        pnl_cmd_add29.setBackground(new java.awt.Color(255, 255, 255));
        pnl_cmd_add29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 157, 65), 1, true));
        pnl_cmd_add29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_cmd_add29MouseClicked(evt);
            }
        });

        jLabel69.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(0, 157, 65));
        jLabel69.setText("Добавить");
        pnl_cmd_add29.add(jLabel69);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_cmd_clear29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_cmd_add29, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_cmd_clear29, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(pnl_cmd_add29, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        txt_student_last_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_student_last_name.setText("Фамилия");
        txt_student_last_name.setBorder(null);
        txt_student_last_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_student_last_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_student_last_nameFocusLost(evt);
            }
        });
        txt_student_last_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_student_last_nameActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 157, 65));

        jSeparator9.setBackground(new java.awt.Color(0, 157, 65));

        txt_student_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_student_name.setText("Имя");
        txt_student_name.setBorder(null);
        txt_student_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_student_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_student_nameFocusLost(evt);
            }
        });
        txt_student_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_student_nameActionPerformed(evt);
            }
        });

        jSeparator10.setBackground(new java.awt.Color(0, 157, 65));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Дата рождения");

        dateChooserCombo1.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("a",
                new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(0, 191, 52),
                    new java.awt.Color(0, 0, 0),
                    javax.swing.BorderFactory.createSoftBevelBorder(javax.swing.border.BevelBorder.RAISED,
                        (java.awt.Color)null,
                        (java.awt.Color)null,
                        (java.awt.Color)null,
                        (java.awt.Color)null),
                    new java.awt.Font("Serif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 153),
                    1.0f),
                new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(153, 153, 255),
                    new java.awt.Color(0, 0, 0),
                    (javax.swing.border.Border)null,
                    new java.awt.Font("Serif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 102),
                    1.0f),
                new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(204, 255, 204),
                    new java.awt.Color(51, 255, 51),
                    (javax.swing.border.Border)null,
                    new java.awt.Font("Serif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 153),
                    1.0f),
                new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(255, 255, 255),
                    new java.awt.Color(0, 0, 102),
                    (javax.swing.border.Border)null,
                    new java.awt.Font("Serif", java.awt.Font.ITALIC, 10),
                    new java.awt.Color(0, 0, 255),
                    1.0f),
                new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(255, 255, 255),
                    new java.awt.Color(0, 0, 0),
                    (javax.swing.border.Border)null,
                    new java.awt.Font("Serif", java.awt.Font.BOLD, 12),
                    new java.awt.Color(0, 0, 255),
                    1.0f),
                new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(255, 255, 255),
                    new java.awt.Color(255, 0, 0),
                    (javax.swing.border.Border)null,
                    new java.awt.Font("Serif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(255, 0, 0),
                    0.7f),
                (datechooser.view.BackRenderer)null,
                true,
                true),
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserCombo1.setCalendarBackground(new java.awt.Color(255, 255, 255));
    dateChooserCombo1.setNothingAllowed(false);
    dateChooserCombo1.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);
    dateChooserCombo1.setFieldFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    dateChooserCombo1.setLocale(new java.util.Locale("ru", "RU", ""));
    dateChooserCombo1.setNavigateFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
    dateChooserCombo1.setCurrentNavigateIndex(0);
    dateChooserCombo1.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
        public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
            dateChooserCombo1OnSelectionChange(evt);
        }
    });
    dateChooserCombo1.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            dateChooserCombo1OnCommit(evt);
        }
    });

    javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
    jPanel17.setLayout(jPanel17Layout);
    jPanel17Layout.setHorizontalGroup(
        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel17Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_student_name)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_student_last_name)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(68, Short.MAX_VALUE))
    );
    jPanel17Layout.setVerticalGroup(
        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel17Layout.createSequentialGroup()
            .addGap(28, 28, 28)
            .addComponent(txt_student_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txt_student_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jLabel13))
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(13, Short.MAX_VALUE))
    );

    jPanel11.setBackground(new java.awt.Color(255, 255, 255));

    jScrollPane29.setBackground(new java.awt.Color(255, 255, 255));
    jScrollPane29.setBorder(null);

    table_student.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ));
    table_student.setGridColor(new java.awt.Color(255, 255, 255));
    table_student.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            table_studentMouseClicked(evt);
        }
    });
    jScrollPane29.setViewportView(table_student);

    txt_header30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txt_header30.setForeground(new java.awt.Color(34, 41, 50));
    txt_header30.setText("Список студентов");

    jSeparator119.setBackground(new java.awt.Color(1, 198, 83));

    txt_search_student.setText("Поиск");
    txt_search_student.setBorder(null);
    txt_search_student.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            txt_search_studentFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            txt_search_studentFocusLost(evt);
        }
    });
    txt_search_student.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            txt_search_studentKeyReleased(evt);
        }
    });

    lbl_cmd_search_gorup1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Resources/Search-30.png"))); // NOI18N

    javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
    jPanel11.setLayout(jPanel11Layout);
    jPanel11Layout.setHorizontalGroup(
        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel11Layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addComponent(txt_header30, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(jPanel11Layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addComponent(jScrollPane29, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addContainerGap())
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addComponent(lbl_cmd_search_gorup1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_search_student)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jSeparator119)
                            .addContainerGap())))))
    );
    jPanel11Layout.setVerticalGroup(
        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel11Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(txt_header30)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(lbl_cmd_search_gorup1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_search_student, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator119, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(44, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout pnl_new_studentLayout = new javax.swing.GroupLayout(pnl_new_student);
    pnl_new_student.setLayout(pnl_new_studentLayout);
    pnl_new_studentLayout.setHorizontalGroup(
        pnl_new_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnl_new_studentLayout.createSequentialGroup()
            .addGroup(pnl_new_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_new_studentLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(txt_header32, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_new_studentLayout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(txt_desc27, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator123, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl_new_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnl_new_studentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_new_studentLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    pnl_new_studentLayout.setVerticalGroup(
        pnl_new_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnl_new_studentLayout.createSequentialGroup()
            .addGroup(pnl_new_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_new_studentLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(txt_header32)
                    .addGap(15, 15, 15)
                    .addComponent(txt_desc27)
                    .addGap(11, 11, 11)
                    .addComponent(jSeparator123, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_new_studentLayout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(127, 127, 127))
        .addGroup(pnl_new_studentLayout.createSequentialGroup()
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jgroup1.add(pnl_new_student);

    javax.swing.GroupLayout pnl_studentLayout = new javax.swing.GroupLayout(pnl_student);
    pnl_student.setLayout(pnl_studentLayout);
    pnl_studentLayout.setHorizontalGroup(
        pnl_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnl_studentLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnl_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jgroup1, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(pnl_header4, javax.swing.GroupLayout.DEFAULT_SIZE, 1122, Short.MAX_VALUE))
            .addContainerGap())
    );
    pnl_studentLayout.setVerticalGroup(
        pnl_studentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_studentLayout.createSequentialGroup()
            .addComponent(pnl_header4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jgroup1))
    );

    pnl_menu.add(pnl_student);

    pnl_group.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
        public void mouseDragged(java.awt.event.MouseEvent evt) {
            pnl_groupMouseDragged(evt);
        }
    });
    pnl_group.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            pnl_groupMousePressed(evt);
        }
    });

    pnl_header.setBackground(new java.awt.Color(0, 157, 65));
    pnl_header.setPreferredSize(new java.awt.Dimension(453, 206));

    lbl_exit_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    lbl_exit_1.setForeground(new java.awt.Color(57, 113, 177));
    lbl_exit_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Resources/1495903985_Gnome-Window-Close-32.png"))); // NOI18N
    lbl_exit_1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            lbl_exit_1MouseClicked(evt);
        }
    });

    lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Resources/1495925307_SEO_WEB_analytics.png"))); // NOI18N

    lbl_logoName.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
    lbl_logoName.setForeground(new java.awt.Color(255, 255, 255));
    lbl_logoName.setText("AnalyticToo");

    lbl_cmd_header_button_create.setBackground(new java.awt.Color(0, 157, 65));
    lbl_cmd_header_button_create.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    lbl_cmd_header_button_create.setForeground(new java.awt.Color(255, 255, 255));
    lbl_cmd_header_button_create.setText("Сформировать группу");
    lbl_cmd_header_button_create.setOpaque(true);
    lbl_cmd_header_button_create.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            lbl_cmd_header_button_createMouseClicked(evt);
        }
    });

    lbl_cmd_header_buttonNew.setBackground(new java.awt.Color(4, 136, 58));
    lbl_cmd_header_buttonNew.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    lbl_cmd_header_buttonNew.setForeground(new java.awt.Color(255, 255, 255));
    lbl_cmd_header_buttonNew.setText("Новая группа");
    lbl_cmd_header_buttonNew.setOpaque(true);
    lbl_cmd_header_buttonNew.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            lbl_cmd_header_buttonNewMouseClicked(evt);
        }
    });

    javax.swing.GroupLayout pnl_headerLayout = new javax.swing.GroupLayout(pnl_header);
    pnl_header.setLayout(pnl_headerLayout);
    pnl_headerLayout.setHorizontalGroup(
        pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnl_headerLayout.createSequentialGroup()
            .addGap(177, 177, 177)
            .addComponent(lbl_cmd_header_buttonNew)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbl_cmd_header_button_create)
            .addGap(0, 0, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_headerLayout.createSequentialGroup()
            .addGap(119, 119, 119)
            .addComponent(lbl_logo)
            .addGap(18, 18, 18)
            .addComponent(lbl_logoName)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_exit_1)
            .addGap(21, 21, 21))
    );
    pnl_headerLayout.setVerticalGroup(
        pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnl_headerLayout.createSequentialGroup()
            .addGroup(pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_headerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl_exit_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_headerLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_headerLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(lbl_logoName))
                        .addComponent(lbl_logo, javax.swing.GroupLayout.Alignment.TRAILING))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
            .addGroup(pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_cmd_header_button_create)
                .addComponent(lbl_cmd_header_buttonNew)))
    );

    jgroup.setLayout(new javax.swing.OverlayLayout(jgroup));

    pnl_new_group_2.setBackground(new java.awt.Color(255, 255, 255));

    txt_header27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txt_header27.setForeground(new java.awt.Color(34, 41, 50));
    txt_header27.setText("Студент");

    jSeparator115.setBackground(new java.awt.Color(1, 198, 83));

    jPanel9.setBackground(new java.awt.Color(255, 255, 255));

    jScrollPane28.setBackground(new java.awt.Color(255, 255, 255));
    jScrollPane28.setBorder(null);

    table_group.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ));
    table_group.setGridColor(new java.awt.Color(255, 255, 255));
    jScrollPane28.setViewportView(table_group);

    txt_header29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txt_header29.setForeground(new java.awt.Color(34, 41, 50));
    txt_header29.setText(" Список групп студентов");

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel9Layout.createSequentialGroup()
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(txt_header29, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel9Layout.setVerticalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel9Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txt_header29)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    table_student_forGroup.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ));
    table_student_forGroup.setGridColor(new java.awt.Color(255, 255, 255));
    table_student_forGroup.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            table_student_forGroupMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(table_student_forGroup);

    jPanel7.setBackground(new java.awt.Color(255, 255, 255));

    pnl_cmd_clear28.setBackground(new java.awt.Color(255, 255, 255));
    pnl_cmd_clear28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 157, 65), 1, true));
    pnl_cmd_clear28.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            pnl_cmd_clear28MouseClicked(evt);
        }
    });

    jLabel66.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel66.setForeground(new java.awt.Color(0, 157, 65));
    jLabel66.setText("Отмена");
    pnl_cmd_clear28.add(jLabel66);

    pnl_cmd_add28.setBackground(new java.awt.Color(255, 255, 255));
    pnl_cmd_add28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 157, 65), 1, true));
    pnl_cmd_add28.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            pnl_cmd_add28MouseClicked(evt);
        }
    });

    jLabel67.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel67.setForeground(new java.awt.Color(0, 157, 65));
    jLabel67.setText("Добавить");
    pnl_cmd_add28.add(jLabel67);

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(pnl_cmd_clear28, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(88, 88, 88)
            .addComponent(pnl_cmd_add28, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(100, Short.MAX_VALUE))
    );
    jPanel7Layout.setVerticalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl_cmd_add28, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(pnl_cmd_clear28, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    choice_group.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            choice_groupMouseClicked(evt);
        }
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            choice_groupMouseReleased(evt);
        }
    });

    txt_header31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txt_header31.setForeground(new java.awt.Color(34, 41, 50));
    txt_header31.setText("Группа");

    javax.swing.GroupLayout pnl_new_group_2Layout = new javax.swing.GroupLayout(pnl_new_group_2);
    pnl_new_group_2.setLayout(pnl_new_group_2Layout);
    pnl_new_group_2Layout.setHorizontalGroup(
        pnl_new_group_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnl_new_group_2Layout.createSequentialGroup()
            .addGroup(pnl_new_group_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_new_group_2Layout.createSequentialGroup()
                    .addGroup(pnl_new_group_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnl_new_group_2Layout.createSequentialGroup()
                            .addGroup(pnl_new_group_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnl_new_group_2Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(txt_header27, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator115, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnl_new_group_2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_new_group_2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txt_header31, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(choice_group, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(141, 141, 141)))
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_new_group_2Layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(34, Short.MAX_VALUE))
    );
    pnl_new_group_2Layout.setVerticalGroup(
        pnl_new_group_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnl_new_group_2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnl_new_group_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(pnl_new_group_2Layout.createSequentialGroup()
                    .addComponent(txt_header27)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSeparator115, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(17, 17, 17)
                    .addGroup(pnl_new_group_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(choice_group, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_header31))
                    .addGap(88, 88, 88)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(22, 22, 22)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jgroup.setLayer(pnl_new_group_2, javax.swing.JLayeredPane.PALETTE_LAYER);
    jgroup.add(pnl_new_group_2);

    pnl_new_group_1.setBackground(new java.awt.Color(255, 255, 255));

    txt_header26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txt_header26.setForeground(new java.awt.Color(34, 41, 50));
    txt_header26.setText("Группа");

    txt_desc26.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
    txt_desc26.setForeground(new java.awt.Color(34, 41, 50));
    txt_desc26.setText("Пожалуйста, заполните все поля");

    jSeparator111.setBackground(new java.awt.Color(1, 198, 83));

    jPanel3.setBackground(new java.awt.Color(255, 255, 255));

    pnl_cmd_clear26.setBackground(new java.awt.Color(255, 255, 255));
    pnl_cmd_clear26.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 157, 65), 1, true));

    jLabel62.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel62.setForeground(new java.awt.Color(0, 157, 65));
    jLabel62.setText("Отмена");
    pnl_cmd_clear26.add(jLabel62);

    pnl_cmd_add26.setBackground(new java.awt.Color(255, 255, 255));
    pnl_cmd_add26.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 157, 65), 1, true));

    jLabel63.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel63.setForeground(new java.awt.Color(0, 157, 65));
    jLabel63.setText("Добавить");
    pnl_cmd_add26.add(jLabel63);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl_cmd_clear26, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(pnl_cmd_add26, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(pnl_cmd_clear26, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
            .addComponent(pnl_cmd_add26, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    jPanel5.setBackground(new java.awt.Color(255, 255, 255));

    jScrollPane27.setBackground(new java.awt.Color(255, 255, 255));
    jScrollPane27.setBorder(null);

    jTable27.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ));
    jTable27.setGridColor(new java.awt.Color(255, 255, 255));
    jScrollPane27.setViewportView(jTable27);

    txt_header28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    txt_header28.setForeground(new java.awt.Color(34, 41, 50));
    txt_header28.setText("Список групп");

    jSeparator114.setBackground(new java.awt.Color(1, 198, 83));

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addComponent(txt_header28, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addComponent(jScrollPane27, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
            .addComponent(jSeparator114)
            .addContainerGap())
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(txt_header28)
            .addGap(43, 43, 43)
            .addComponent(jSeparator114, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27)
            .addComponent(jScrollPane27, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
            .addContainerGap())
    );

    jPanel6.setBackground(new java.awt.Color(255, 255, 255));

    jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
    jLabel7.setText("<html>Для выбора, зажмите клавишу Shift, \n<p>и выбирете обе даты </html>");

    jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel6.setText("Дата начала - дата окончания");

    start_finish_date.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("a",
            new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(0, 191, 52),
                new java.awt.Color(0, 0, 0),
                javax.swing.BorderFactory.createSoftBevelBorder(javax.swing.border.BevelBorder.RAISED,
                    (java.awt.Color)null,
                    (java.awt.Color)null,
                    (java.awt.Color)null,
                    (java.awt.Color)null),
                new java.awt.Font("Serif", java.awt.Font.PLAIN, 12),
                new java.awt.Color(0, 0, 153),
                1.0f),
            new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(153, 153, 255),
                new java.awt.Color(0, 0, 0),
                (javax.swing.border.Border)null,
                new java.awt.Font("Serif", java.awt.Font.PLAIN, 12),
                new java.awt.Color(0, 0, 102),
                1.0f),
            new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(204, 255, 204),
                new java.awt.Color(51, 255, 51),
                (javax.swing.border.Border)null,
                new java.awt.Font("Serif", java.awt.Font.PLAIN, 12),
                new java.awt.Color(0, 0, 153),
                1.0f),
            new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(255, 255, 255),
                new java.awt.Color(0, 0, 102),
                (javax.swing.border.Border)null,
                new java.awt.Font("Serif", java.awt.Font.ITALIC, 10),
                new java.awt.Color(0, 0, 255),
                1.0f),
            new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(255, 255, 255),
                new java.awt.Color(0, 0, 0),
                (javax.swing.border.Border)null,
                new java.awt.Font("Serif", java.awt.Font.BOLD, 12),
                new java.awt.Color(0, 0, 255),
                1.0f),
            new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(255, 255, 255),
                new java.awt.Color(255, 0, 0),
                (javax.swing.border.Border)null,
                new java.awt.Font("Serif", java.awt.Font.PLAIN, 12),
                new java.awt.Color(255, 0, 0),
                0.7f),
            (datechooser.view.BackRenderer)null,
            true,
            true),
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
start_finish_date.setCalendarBackground(new java.awt.Color(255, 255, 255));
start_finish_date.setNothingAllowed(false);
start_finish_date.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);
start_finish_date.setFieldFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
start_finish_date.setLocale(new java.util.Locale("ru", "RU", ""));
start_finish_date.setNavigateFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
start_finish_date.setCurrentNavigateIndex(0);
start_finish_date.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
    public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
        start_finish_dateOnSelectionChange(evt);
    }
    });
    start_finish_date.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            start_finish_dateOnCommit(evt);
        }
    });

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(start_finish_date, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(29, Short.MAX_VALUE))
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel6)
            .addGap(1, 1, 1)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(start_finish_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(85, 85, 85))
    );

    jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel10.setText("Преподаватель");

    jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel11.setText("Предмет");

    javax.swing.GroupLayout pnl_new_group_1Layout = new javax.swing.GroupLayout(pnl_new_group_1);
    pnl_new_group_1.setLayout(pnl_new_group_1Layout);
    pnl_new_group_1Layout.setHorizontalGroup(
        pnl_new_group_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnl_new_group_1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnl_new_group_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_new_group_1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(txt_header26, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_new_group_1Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(txt_desc26, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_new_group_1Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(pnl_new_group_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(choiceTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(pnl_new_group_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(choiceDescipline, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnl_new_group_1Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSeparator111, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    pnl_new_group_1Layout.setVerticalGroup(
        pnl_new_group_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnl_new_group_1Layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(txt_header26)
            .addGap(15, 15, 15)
            .addComponent(txt_desc26)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jSeparator111, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(15, 15, 15)
            .addGroup(pnl_new_group_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_new_group_1Layout.createSequentialGroup()
                    .addComponent(jLabel10)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(choiceTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_new_group_1Layout.createSequentialGroup()
                    .addComponent(jLabel11)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(choiceDescipline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(22, 22, 22)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(123, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_new_group_1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    jgroup.add(pnl_new_group_1);

    javax.swing.GroupLayout pnl_groupLayout = new javax.swing.GroupLayout(pnl_group);
    pnl_group.setLayout(pnl_groupLayout);
    pnl_groupLayout.setHorizontalGroup(
        pnl_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnl_groupLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnl_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_groupLayout.createSequentialGroup()
                    .addComponent(jgroup)
                    .addContainerGap())
                .addComponent(pnl_header, javax.swing.GroupLayout.DEFAULT_SIZE, 1132, Short.MAX_VALUE)))
    );
    pnl_groupLayout.setVerticalGroup(
        pnl_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_groupLayout.createSequentialGroup()
            .addComponent(pnl_header, 163, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jgroup))
    );

    pnl_menu.add(pnl_group);

    jLayeredPane1.setLayer(pnl_sidebar, javax.swing.JLayeredPane.PALETTE_LAYER);
    jLayeredPane1.setLayer(pnl_menu, javax.swing.JLayeredPane.MODAL_LAYER);

    javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
    jLayeredPane1.setLayout(jLayeredPane1Layout);
    jLayeredPane1Layout.setHorizontalGroup(
        jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(pnl_sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGroup(jLayeredPane1Layout.createSequentialGroup()
            .addGap(211, 211, 211)
            .addComponent(pnl_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jLayeredPane1Layout.setVerticalGroup(
        jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(pnl_sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(pnl_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    getContentPane().add(jLayeredPane1, java.awt.BorderLayout.CENTER);

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

    }//GEN-LAST:event_formMousePressed

    private void pnl_groupMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_groupMouseDragged

    }//GEN-LAST:event_pnl_groupMouseDragged

    private void pnl_groupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_groupMousePressed


    }//GEN-LAST:event_pnl_groupMousePressed

    private void menu_item_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_item_1MousePressed
        setItemColoer(menu_item_1);
        resetItemColoer(menu_item_2);
    }//GEN-LAST:event_menu_item_1MousePressed

    private void menu_item_2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_item_2MouseReleased
        setItemColoer(menu_item_2);
        resetItemColoer(menu_item_1);
    }//GEN-LAST:event_menu_item_2MouseReleased

    private void pnl_sidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_sidebarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_pnl_sidebarMouseDragged

    private void pnl_sidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_sidebarMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_pnl_sidebarMousePressed

    private void menu_item_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_item_1MouseClicked
        pnl_group.setVisible(false);
        pnl_student.setVisible(true);

    }//GEN-LAST:event_menu_item_1MouseClicked

    private void menu_item_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_item_2MouseClicked
         pnl_group.setVisible(true);
         pnl_student.setVisible(false);
         pnl_new_group_1.setVisible(true);


          int sizeTeacher = dbg.loadToChoice(tag.DB_NAME+"."+tag.TEACHERS_TABLE, tag.LASTNAME+"").size() ;
           for(int i = 0; i < sizeTeacher; i++){
               choiceTeacher.addItem(dbg.loadToChoice(tag.DB_NAME+"."+tag.TEACHERS_TABLE, tag.LASTNAME+"").get(i).toString());
           }

           int sizeDiscipline = dbg.loadToChoice(tag.DB_NAME+"."+tag.DISCIPLINE_TABLE, tag.DISCIPLINE_NAME+"").size() ;
           for(int i = 0; i < sizeDiscipline; i++){
               choiceDescipline.addItem(dbg.loadToChoice(tag.DB_NAME+"."+tag.DISCIPLINE_TABLE, tag.DISCIPLINE_NAME+"").get(i).toString());
           }
    }//GEN-LAST:event_menu_item_2MouseClicked

    private void pnl_studentMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_studentMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_studentMouseDragged

    private void pnl_studentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_studentMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_studentMousePressed

    private void lbl_cmd_header_buttonNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cmd_header_buttonNewMouseClicked
        setLblColor(lbl_cmd_header_buttonNew);
        resetLblColor(lbl_cmd_header_button_create);
        pnl_new_group_1.setVisible(true);
        pnl_new_group_2.setVisible(false);
        pnl_group.setVisible(true);

    }//GEN-LAST:event_lbl_cmd_header_buttonNewMouseClicked

    private void lbl_cmd_header_button_createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cmd_header_button_createMouseClicked
        setLblColor(lbl_cmd_header_button_create);
        resetLblColor(lbl_cmd_header_buttonNew);
        pnl_new_group_1.setVisible(false);
        pnl_new_group_2.setVisible(true);
        setValueToTableGroupStudent();

          int sizeTeacher = dbg.loadToChoice(tag.DB_NAME+"."+tag.GROUP_TABLE, tag.ID+"").size() ;
           for(int i = 0; i < sizeTeacher; i++){
               choice_group.addItem(dbg.loadToChoice(tag.DB_NAME+"."+tag.GROUP_TABLE, tag.ID+"").get(i).toString());
           }
    }//GEN-LAST:event_lbl_cmd_header_button_createMouseClicked

    private void lbl_exit_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit_1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbl_exit_1MouseClicked

    private void lbl_exit_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit_5MouseClicked
                System.exit(0);
    }//GEN-LAST:event_lbl_exit_5MouseClicked

    private void pnl_cmd_add29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_cmd_add29MouseClicked
         db.studentTableInsert(txt_student_name.getText(), txt_student_last_name.getText(),dateChooserCombo1.getSelectedDate());
         table_student.setModel(DbUtils.resultSetToTableModel(db.loadTable(tag.DB_NAME+"."+tag.STUDENT_TABLE, null)));
         txt_student_name.setText("Имя");
         txt_student_last_name.setText("Фамилия");
    }//GEN-LAST:event_pnl_cmd_add29MouseClicked

    private void txt_student_last_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_student_last_nameFocusGained
       txt_student_last_name.setText(null);
    }//GEN-LAST:event_txt_student_last_nameFocusGained

    private void txt_student_last_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_student_last_nameFocusLost

    }//GEN-LAST:event_txt_student_last_nameFocusLost

    private void txt_student_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_student_nameFocusGained
       txt_student_name.setText(null);
    }//GEN-LAST:event_txt_student_nameFocusGained

    private void txt_student_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_student_nameFocusLost

    }//GEN-LAST:event_txt_student_nameFocusLost

    private void table_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_studentMouseClicked
        int row = table_student.getSelectedRow();
        Integer  table_click = (Integer) (table_student.getModel().getValueAt(row, 0));
        setValueToField(table_click);

    }//GEN-LAST:event_table_studentMouseClicked

    private void txt_student_last_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_student_last_nameActionPerformed
            db.updateTableStudent(studentId,txt_student_name.getText(), txt_student_last_name.getText(),dateChooserCombo1.getSelectedDate());
            table_student.setModel(DbUtils.resultSetToTableModel(db.loadTable(tag.DB_NAME+"."+tag.STUDENT_TABLE, null)));
            setValueToField(studentId);
    }//GEN-LAST:event_txt_student_last_nameActionPerformed

    private void txt_student_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_student_nameActionPerformed
            db.updateTableStudent(studentId,txt_student_name.getText(), txt_student_last_name.getText(),dateChooserCombo1.getSelectedDate());
            table_student.setModel(DbUtils.resultSetToTableModel(db.loadTable(tag.DB_NAME+"."+tag.STUDENT_TABLE, null)));
            setValueToField(studentId);
    }//GEN-LAST:event_txt_student_nameActionPerformed

    private void dateChooserCombo1OnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dateChooserCombo1OnSelectionChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserCombo1OnSelectionChange

    private void dateChooserCombo1OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserCombo1OnCommit
        db.updateTableStudent(studentId,txt_student_name.getText(), txt_student_last_name.getText(),dateChooserCombo1.getSelectedDate());
        table_student.setModel(DbUtils.resultSetToTableModel(db.loadTable(tag.DB_NAME+"."+tag.STUDENT_TABLE, null)));
    }//GEN-LAST:event_dateChooserCombo1OnCommit

    private void pnl_cmd_clear29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_cmd_clear29MouseClicked
       txt_student_name.setText("Имя");
       txt_student_last_name.setText("Фамилия");
       studentId = 0;
    }//GEN-LAST:event_pnl_cmd_clear29MouseClicked

    private void txt_search_studentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_search_studentFocusGained
        txt_search_student.setText(null);

    }//GEN-LAST:event_txt_search_studentFocusGained

    private void txt_search_studentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_search_studentFocusLost
        txt_search_student.setText("Поиск");
    }//GEN-LAST:event_txt_search_studentFocusLost

    private void txt_search_studentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_studentKeyReleased
         table_student.setModel(DbUtils.resultSetToTableModel(db.searchStudentInTable(txt_student_last_name.getText(),  null)));
    }//GEN-LAST:event_txt_search_studentKeyReleased

    private void pnl_new_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_new_studentMouseClicked
        setValueToTableStudent();
        txt_search_student.setText("Поиск");
    }//GEN-LAST:event_pnl_new_studentMouseClicked

    private void start_finish_dateOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_start_finish_dateOnCommit

    }//GEN-LAST:event_start_finish_dateOnCommit

    private void start_finish_dateOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_start_finish_dateOnSelectionChange

    }//GEN-LAST:event_start_finish_dateOnSelectionChange

    private void pnl_cmd_add28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_cmd_add28MouseClicked
       int[] selectedRows = table_student_forGroup.getSelectedRows();
                    for(int i = 0; i < selectedRows.length; i++) {
                         int selIndex = selectedRows[i];
                         TableModel model = table_student_forGroup.getModel();
                         Object value = model.getValueAt(selIndex, 0);
                        s.add((String) value.toString());
                    }
        JOptionPane.showMessageDialog(rootPane, s.toString());
    }//GEN-LAST:event_pnl_cmd_add28MouseClicked

    private void table_student_forGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_student_forGroupMouseClicked

    }//GEN-LAST:event_table_student_forGroupMouseClicked

    private void choice_groupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice_groupMouseClicked

    }//GEN-LAST:event_choice_groupMouseClicked

    private void choice_groupMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice_groupMouseReleased
        String id = choice_group.getSelectedItem();
        JOptionPane.showMessageDialog(rootPane, id.toString());
        table_group.setModel(DbUtils.resultSetToTableModel(dbg.loadStudentGroup(id, null)));

    }//GEN-LAST:event_choice_groupMouseReleased

    private void pnl_cmd_clear28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_cmd_clear28MouseClicked
        String idGroup = choice_group.getSelectedItem();
        for(int i=0; i<s.size(); i++){
            dbg.studentTableInsert(idGroup, s.get(i));
        }
        
        s.clear();
               table_group.setModel(DbUtils.resultSetToTableModel(dbg.loadStudentGroupClear(null)));
    }//GEN-LAST:event_pnl_cmd_clear28MouseClicked

     private void setLblColor(JLabel lbl){
        lbl.setBackground(new Color(4,136,58));
    }

     private void resetLblColor(JLabel lbl){
        lbl.setBackground(new Color(0,157,65));
    }

    private void setItemColoer(JLabel lbl){
        lbl.setForeground(new Color(166, 166, 166));
    }

     private void resetItemColoer(JLabel lbl){
        lbl.setForeground(new Color(255, 255, 255));
    }


     private void setValueToField(int table_click){
         Calendar selectDate =  new GregorianCalendar();;
          txt_student_name.setText(db.getValueFromTableStudent(table_click).get("first_name").toString());
          txt_student_last_name.setText(db.getValueFromTableStudent(table_click).get("last_name").toString());
            selectDate.setTime((java.sql.Date) db.getValueFromTableStudent(table_click).get("date_birthday"));
            dateChooserCombo1.setSelectedDate(selectDate);
            studentId = (Integer) db.getValueFromTableStudent(table_click).get("id");
     }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choiceDescipline;
    private java.awt.Choice choiceTeacher;
    private java.awt.Choice choice_group;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator111;
    private javax.swing.JSeparator jSeparator114;
    private javax.swing.JSeparator jSeparator115;
    private javax.swing.JSeparator jSeparator119;
    private javax.swing.JSeparator jSeparator123;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable27;
    private javax.swing.JLayeredPane jgroup;
    private javax.swing.JLayeredPane jgroup1;
    private javax.swing.JLabel lbl_cmd_header_buttonNew;
    private javax.swing.JLabel lbl_cmd_header_button_create;
    private javax.swing.JLabel lbl_cmd_search_gorup1;
    private javax.swing.JLabel lbl_exit_1;
    private javax.swing.JLabel lbl_exit_5;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_logo4;
    private javax.swing.JLabel lbl_logoName;
    private javax.swing.JLabel lbl_logoName4;
    private javax.swing.JLabel menu_item_1;
    private javax.swing.JLabel menu_item_2;
    private javax.swing.JPanel pnl_cmd_add26;
    private javax.swing.JPanel pnl_cmd_add28;
    private javax.swing.JPanel pnl_cmd_add29;
    private javax.swing.JPanel pnl_cmd_clear26;
    private javax.swing.JPanel pnl_cmd_clear28;
    private javax.swing.JPanel pnl_cmd_clear29;
    private javax.swing.JPanel pnl_group;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_header4;
    private javax.swing.JLayeredPane pnl_menu;
    private javax.swing.JPanel pnl_new_group_1;
    private javax.swing.JPanel pnl_new_group_2;
    private javax.swing.JPanel pnl_new_student;
    private javax.swing.JPanel pnl_sidebar;
    private javax.swing.JPanel pnl_student;
    private datechooser.beans.DateChooserCombo start_finish_date;
    private javax.swing.JTable table_group;
    private javax.swing.JTable table_student;
    private javax.swing.JTable table_student_forGroup;
    private javax.swing.JLabel txt_desc26;
    private javax.swing.JLabel txt_desc27;
    private javax.swing.JLabel txt_header26;
    private javax.swing.JLabel txt_header27;
    private javax.swing.JLabel txt_header28;
    private javax.swing.JLabel txt_header29;
    private javax.swing.JLabel txt_header30;
    private javax.swing.JLabel txt_header31;
    private javax.swing.JLabel txt_header32;
    private javax.swing.JTextField txt_search_student;
    private javax.swing.JTextField txt_student_last_name;
    private javax.swing.JTextField txt_student_name;
    // End of variables declaration//GEN-END:variables
}
